### ISSUE TITLE
Various functionality doesn't activate in channels with '!' in the channel name

### ISSUE THREAD

**Issue by sdyether** [goshuirc/goshu#2]
Tested in fresh channel to ensure it wasn't the bot being on a channel blocklist

**Comment by DanielOaks** [comment]
Huh, that's a very strange issue, not sure where the problem would lie.

I'll test to confirm when I'm at a PC, thanks for the issue.

**Comment by DanielOaks** [comment]
Actually, just curious. Does the bot work in channels without "!" in the
title?

I'm not sure how robust the code is for asking for the API key, and if
that't not in there that could be why it's failing.

**Comment by sdyether** [comment]
Yep, the link describing works fine in channels without this character in the name.

Tested further and the issue happens regardless of whether the character is trailing  (#osu!), or not (#test!test). 
 Hopefully the bug isn't at a lower level third-party library that is parsing without realising '!' is an allowed character in Rizon channel name (I haven't looked at the code to see where this kind of stuff is handled).

**Comment by DanielOaks** [comment]
Yeah shouldn't be something like that, I believe we're very lenient with
that sort of thing. I'll take a bit of a look and trace down where it's
happening.

Just curious, you're using the `goshu3` branch? (the main branch)

**Comment by sdyether** [comment]
Assuming that is what the Rizon user 'imouto-baka' is running.

Note I think this issue is not specific to the youtube link describing; it was just the main functionality I was interested in.

Tested 'google functionality and it doesn't work either in '!' channels, so I will rename this issue.

**Comment by DanielOaks** [comment]
This is fixed by df4ebe61ff83450638e3ede609081a459ecb6174 and will be pushed online shortly. Thanks very much for letting me know, getting reports like this is much appreciated!
